
service: ftc-aficlark

provider:
  name: aws
  runtime: java8
  region: us-west-2

package:
  artifact: build/distributions/hello.zip

functions:
  hello:
    handler: com.serverless.Handler
    events:
      - http:
          path: hello-java
          method: get
